INDEX ON EDAD TAG EDAD
INDEX ON EDAD TAG TIP_EDAD
INDEX ON SEXO TAG SEXO

INDEX ON DIAGNOST1 TAG DIAGNOST1
INDEX ON LABCONF1 TAG LABCONF1
INDEX ON CODIGO1 TAG CODIGO1

INDEX ON DIAGNOST2 TAG DIAGNOST2
INDEX ON LABCONF2 TAG LABCONF2
INDEX ON CODIGO2 TAG CODIGO2

INDEX ON DIAGNOST3 TAG DIAGNOST3
INDEX ON LABCONF3 TAG LABCONF3
INDEX ON CODIGO3 TAG CODIGO3


INDEX ON DIAGNOST4 TAG DIAGNOST4
INDEX ON LABCONF4 TAG LABCONF4
INDEX ON CODIGO4 TAG CODIGO4

INDEX ON DIAGNOST5 TAG DIAGNOST5
INDEX ON LABCONF5 TAG LABCONF5
INDEX ON CODIGO5 TAG CODIGO5

INDEX ON DIAGNOST6 TAG DIAGNOST6
INDEX ON LABCONF6 TAG LABCONF6
INDEX ON CODIGO6 TAG CODIGO6

